protected/controllers/OrdersController.php
<?php
/**
 * @author Imran Ali Namazi <imran@cselian.com>
 * @link http://tg.cselian.com/showcase/e-vend
 * @copyright Copyright &copy; 2012-2013 cselian.com
 * @license http://tg.cselian.com/licenses/e-vend
 */

class OrdersController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		$this->menuOnTop();
		return $this->getAccessRules();
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model = $this->loadModel($id);
		if (isset($_GET['mails']) || isset($_GET['mail']))
		{
			$mails = isset($_GET['mail']) ? array($_GET['mail']) 
				: array('created', 'approval', 'approved', 'distrib', 'paid');
			FlashMessages::AddCurrent('Test emails sent for: ' . implode(', ', $mails));
			foreach ($mails as $mail) AppMails::send('order-' . $mail, $model);
		}
		
		$this->render('view',array(
			'model'=>$model,
			'addr' => '', 'attsOnly' => false, // since called by pay.php
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionAdd()
	{
		$model=new Order;

		$cartItems = Yii::app()->session['cart'];
		if ($cartItems == null || count($cartItems) == 0)
			throw new CHttpException(400, "No cart items to add. Please go back and try again");
		
		$items = array(); $amt = 0;
		foreach ($cartItems as $i) {
			$data = array(
				'order_id' => 0,
				'product_id' => $i['id'],
				'quantity' => $i['qty'],
				'price' => $i['final'],
				'calculation' => $i['calc'],
				'variation' => $i['varn'],
			);
			$amt += $i['qty'] * $i['final'];
			$items[] = $data;
		}
		
		$order = new Order;
		$buyer = Buyer::model()->findByPk(UserIdentity::context('buyer'));
		$address = $_POST['address'] != '' ? Address::model()->findByPk($_POST['address']) : null;
		$order->attributes = array(
			'buyer_id' => UserIdentity::context('buyer'),
			'user_id' => UserIdentity::context('user'),
			'order_date' => date('Y-m-d H:i:s'),
			'status' => 1,
			'amount' => $amt,
			'address_id' => $_POST['address'],
			'billing_address_id' => $_POST['billingAddress'],
			'payment_type' => $_POST['payment_type'],
			'verification'=> AppHelper::generatePassword(4),
			'despatcher_id' => $address != null ? $address->assigned_to_id : $buyer->assigned_to_id, 
			'stock_nos' => '',
		);

		$approve = AppBuyers::isApprovalRequired();
		if ($approve) $order->approved = -1;
		
		if (!$order->save())
			print_r($order->getErrors());

		$orderId = $order->id;
		foreach ($items as $i)
		{
			$i['order_id'] = $orderId;
			$itm = new OrderItem;
			$itm->attributes = $i;
			if (!$itm->save($i))
				print_r($itm->getErrors());
		}
		
		unset(Yii::app()->session['cart']);
		FlashMessages::Add('Your Order has been placed and will be ' . ($approve ? 'approved' : 'delivered') . ' shortly. You should receive an e-mail now, confirming the order.');
		AppMails::send('order-created', $order, array('approval_required' => $approve));
		if ($approve) AppMails::send('order-approval', $order);
		else if ($order->despatcher_id != null) AppMails::send('order-distrib', $order);
		$this->redirect(array($order-payment_type == 1 ? 'pay' : 'view','id'=>$orderId));
	}

	public function actionPay($id)
	{
		$model=$this->loadModel($id);
		
		Yii::import('application.extensions.vpc.PaymentClient');
		PaymentClient::AddPayTestMessage();
		
		if ($model->payment_type != 1)
		{
			FlashMessages::Add('Redirected to View Order. You cannot view Online Payment details (/orders/pay/#nr) unless the payment type is Gateway.');
			$this->redirect(array('view','id'=>$id));
			return;
		}

		$data = array('model'=>$model);
		$isBuyer = $this->user_is('buyer');
		if ($isBuyer && isset($_GET['ret']) && $model->payment_ref == '')
		{
			unset($_GET['id']);
			unset($_GET['ret']); //affects hash calculation otherwise
			$pg = $_GET['pg'];
			unset($_GET['pg']);
			$ret = PaymentClient::GetReturnData($_GET, $pg);
			$det = PaymentClient::GetDetails($ret, $pg);

			$model->payment_details = serialize($det);
			
			if ($ret['hashOk'] && !$ret['errorExists'] && $ret['message'] == 'Approved')
			{
				$model->payment_ref = $ret['transactionNo']; // dont set if fails, used to show links
				$model->payment_confirmed = 1;
				AppStock::UpdateStock($model, $model->despatcher_id);
				AppMails::send('order-paid', $model);
				FlashMessages::AddCurrent('Your payment was succesful', 'success');
			}
			else
			{
				$model->payment_confirmed = 0;
				FlashMessages::AddCurrent(sprintf('%s <br/>Click %s to try again. Hash Status: %s.',
					$ret['message'], CHtml::link('here', array('/orders/pay/' . $id)), $ret['hashValidated']), 'error');
			}
			
			$model->save();
		}
		else if ($isBuyer && $model->isUnpaid())
		{
			$url = Yii::app()->createAbsoluteUrl('/orders/pay/' . $id) . '?ret=1';
			$pgs = PaymentClient::GetPGs();
			$links = array();
			foreach ($pgs as $key=>$name)
			{
				$img = CHtml::image(sprintf('%s/img/pg/%s.png', Yii::app()->baseurl, $key), $name, array('height' => 40));
				$links[] = CHtml::link($img, PaymentClient::GetSendUrl($model, $url . '&pg=' . $key, $key), array('title' => $name));
			}
			$data['payLink'] = '<span>Pay With</span> ' . implode(' <span>or</span> ', $links) . '.';
		}
		
		if ($this->user_is('superadmin') && $model->payment_details != '' && $model->payment_details != null)
		{
			$data['details'] = unserialize($model->payment_details);
		}
		
		$data['pgs'] = PaymentClient::GetPGs();
		$data['dummy'] = PaymentClient::GetDummyLinks();
		
		$this->render('pay', $data);
	}

	public function actionPurge($id)
	{
		if (isset($_GET['export']))
		{
			$file = $this->purgeFile($id);
			header(sprintf('Content-Disposition: attachment; filename=%s', $file['name']));
			echo $file['content'];
			return;
		}
		
		$model=$this->loadModel($id, 1);
		
		if (isset($_GET['delete']))
		{
			//$model = null;
			if ($model == null) {
				FlashMessages::AddCurrent('This order must have already been deleted.', 'error');
			} else {
				$others = $model->otherOrders();
				if ($others) {
					FlashMessages::AddCurrent(sprintf('Cannot delete since user has other order(s): %s.', implode(', ', $others)), 'error');
				} else {
					$deleted = array();
					$log = $this->site_file('protected/data/purged/order-'.$id.'.log');
					foreach ($model->orderItems as $itm) $deleted[] = AppHelper::deleteModel($itm, $log);
					$user = $model->user;
					$deleted[] = AppHelper::deleteModel($model, $log);
					foreach ($user->addresses as $itm) $deleted[] = AppHelper::deleteModel($itm, $log);
					$deleted[] = AppHelper::deleteModel($user, $log);
					FlashMessages::AddCurrent('Deleted: ' . implode(', ', $deleted));
					$model = null; // since just deleted
				}
			}
		}
		
		$can = $model != null && AppBuyers::canPurge($model->buyer_id);
		if ($model != null && !$can)
		{
			FlashMessages::AddCurrent(sprintf("This order cannot be purged. Please check the buyer configuration %s then %s."
					, CHtml::link('here', array('/buyers/update/' . $model->buyer_id))
					, CHtml::link('refresh the cache', array('/site/admin/?action=clear'))
			));
		}

		$this->render('purge',array(
			'id' => $id,
			'model'=>$model,
			'canPurge' => $can
		));
	}
	
	public function purgeFile($id, $data = null)
	{
		$name = sprintf('order-%s-%s.txt',
			$id,
			str_replace(' ', '-', strtolower(AppEnv::name())) );
		$file = $this->site_file('protected/data/purged/' . $name);
		if ($data)
			file_put_contents($file, $data);
		else
			return array('name' => $name, 'content' => file_get_contents($file));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		$errors = null;
		$messages = null;
		//print_r($_POST);
		
		if (isset($_POST['Order']))
		{
			$pb = $_POST['Order'];
			$setter = new FieldSetter;
			$this->_updateOrderItems($setter);
			
			$statuses = AppLookups::$orderStatuses;
			$statusFmt = 'Cannot %s Order if status is %s';
			//1 Created, 2 Under Processing, 3 Despatched, 4 Delivered, 9 Cancelled
			if ($this->user_is('buyernonadmin'))
			{
				if (isset($pb['address']) && $pb['address'] != $model->address_id)
					$model->address_id = $setter->getValue($model->address_id, $pb['address'], $model->status == 1, 'Address Changed', 'Cannot Change Address unless it is just created');
				
				if (isset($pb['status_cancel'])) {
					$model->status = $setter->getValue($model->status, 9, $model->status == 1, 'Order Cancelled', 'Cannot Cancel Order unless it is just created');
					AppStock::UpdateStock($model, $model->despatcher_id, 1);
				}

				if (isset($pb['payment_ref']))
					$model->payment_ref = $setter->getValue($model->payment_ref, $pb['payment_ref'], $model->payment_type == 3, 
						'Set Payment Reference for NEFT', 'Cannot Set Payment Reference unless type is NEFT');
				if (isset($pb['payment_date']))
					$model->payment_date = $setter->getValue($model->payment_date, Formatter::dateForSql($pb['payment_date']), $model->payment_type == 3, 
						'Set Payment Date for NEFT', 'Cannot Set Payment Date unless type is NEFT');
			}
			else if ($this->user_is('distributor'))
			{
				if (isset($pb['status_begin'])) {
					if (!$setter->addErrorIfOneOf('Order Begun', $model->status, array(2, 3, 4, 9), $statusFmt, 'Begin', $statuses))

protected/views/orders/_admin-status.php
<tr<?php Formatter::altRow($index); ?>>
<?php if (!isset($data)) { ?>
	<th>What*</th>
	<th>Virtual Status**</th>
	<th>Status</th>
	<th>Approval</th>
	<th>Payment</th>
<?php } else { ?>
	<td><?php echo $data->payment_details; ?></td>
	<td><?php echo $data->formatStatus(); ?></td>
	<td><?php echo $data->status . ' => ' . AppLookups::OrderStatus($data->status); ?></td>
	<td><?php echo $data->approved . ' => ' . $data->formatApproval(); ?></td>
	<td><?php echo Formatter::bool($data->payment_confirmed); ?></td>
<?php } ?>
</tr>

protected/views/orders/_form.php
<?php
$form=$this->beginWidget('CActiveForm', array(
	'id'=>'order-form',
	'enableAjaxValidation'=>false,
));

$address = $this->user_is('buyernonadmin') && $model->status == 1
	? CHtml::dropDownList('Order[address]', $model->address_id, $addresses)
	: $model->formatAddress();

function statusAction($status, $name, $disp = null)
{
	if ($disp == null) $disp = ucfirst($name) . ' Order';
	$cbname = 'Order[status_' . $name . ']';
	$status .= ' ' . CHtml::checkBox($cbname) . CHtml::label($disp, 'Order_status_' . $name);
	return $status;
}

$status = CHtml::label(AppLookups::OrderStatus($model->status), '', array('class' => 'first'));
$approval = $model->formatApproval();
$verification = $model->verification;
$despatcher = Formatter::displayObject($model->despatcher, '')
	. ($model->despatcher != null ? ' <br/>Address: ' . Address::formatEx($model->despatcher) : '');
$despatcherRef = $model->despatcher_reference;
$pytRef = $model->payment_ref;
$pytDate = Formatter::date($model->payment_date, 0);
$pytConf = Formatter::bool($model->payment_confirmed);

if ($this->user_is('buyernonadmin'))
{
	if ($model->status == 1)
	{
		$status = statusAction($status, 'cancel');
		if (!$model->isUnpaid())
			$status .= ' * <span class="small-note">' . AppEnv::get('cancellation-charge-note', 'cancellation-charge-note') . '</span>';
	}
	
	if ($model->payment_type == 3 && !$model->payment_confirmed) // NEFT
	{
		$pytRef = CHtml::textField('Order[payment_ref]', $model->payment_ref);
		$pytDate = AppHelper::DatePicker($this, $model, 'payment_date');
	}
}
else if ($this->user_is('distributor'))
{
	if ($model->status == 1)
		$status = statusAction($status, 'begin');
	
	if ($model->status == 1 || $model->status == 2)
		$status = statusAction($status, 'despatch');
	
	if ($model->status == 1 || $model->status == 2 || $model->status == 3)
	{
		$status = statusAction($status, 'deliver', 'Verify && Deliver');
		$verification = CHtml::textField('Order[verification]');
		$despatcherRef = CHtml::textField('Order[despatcher_reference]', $model->despatcher_reference);
	}
	
	if (!$model->payment_confirmed)
	{
		$pytConf = CHtml::checkBox('Order[payment_confirmed]');
		if ($model->payment_type == 2) // COD
		{
			$pytRef = CHtml::textField('Order[payment_ref]', $model->payment_ref);
			$pytDate = AppHelper::DatePicker($this, $model, 'payment_date');
		}
	}
}
else if ($this->user_is('superorbuyeradmin'))
{
	if ($this->user_is('superadmin') && $model->status == 1)
		$despatcher = CHtml::dropDownList('Order[despatcher_id]', $model->despatcher_id, Formatter::includeBlank(AppLookups::Distributors()));
	
	if ($model->needsApprovalOrRejection())
		$approval .= 
			 ' ' . CHtml::checkBox('Order[approved]') . CHtml::label('Approve Order', 'Order_approved')
			.' ' . CHtml::checkBox('Order[rejected]') . CHtml::label('Reject Order', 'Order_rejected');
}

$this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'htmlOptions' => array('class' => 'detail-view viewandedit'),
	'attributes'=>array(
		'id',
		array('label'=>$model->getAttributeLabel('buyer_id'), 'type'=>'raw', 'value'=>Formatter::displayObject($model->buyer)),
		array('label'=>$model->getAttributeLabel('user_id'), 'type'=>'raw', 'value'=>User::link($model->user, $model->buyer)),
		array('label'=>$model->getAttributeLabel('address_id'), 'type'=>'raw', 'value'=>$address),
		array('label'=>$model->getAttributeLabel('order_date'), 'type'=>'raw', 'value'=>Formatter::date($model->order_date, 1)),
		array('label'=>$model->getAttributeLabel('amount'), 'type'=>'raw', 'value'=>Formatter::amount($model->amount)),
		array('label'=>$model->getAttributeLabel('verification'), 'type'=>'raw', 'value'=>$verification),
		array('label'=>$model->getAttributeLabel('status'), 'type'=>'raw', 'value'=>$status),
		array('label'=>$model->getAttributeLabel('approval'), 'type'=>'raw', 'value'=>$approval),
		array('label'=>$model->getAttributeLabel('despatched_date'), 'type'=>'raw', 'value'=>Formatter::date($model->despatched_date, 1)),
		array('label'=>$model->getAttributeLabel('despatcher_reference'), 'type'=>'raw', 'value'=> $despatcherRef),
		array('label'=>$model->getAttributeLabel('despatcher_id'), 'type'=>'raw', 'value'=>$despatcher),
		array('label'=>$model->getAttributeLabel('payment_type'), 'type'=>'raw', 'value'=>AppLookups::PaymentType($model->payment_type)),
		array('label'=>$model->getAttributeLabel('payment_ref'), 'type'=>'raw', 'value'=>$pytRef),
		array('label'=>$model->getAttributeLabel('payment_date'), 'type'=>'raw', 'value'=>$pytDate),
		array('label'=>$model->getAttributeLabel('payment_confirmed'), 'type'=>'raw', 'value'=>$pytConf),
	),
)); ?>

<?php if ($this->user_is('distributor')) { ?>
<br /><br />
<h2>Items</h2>

<table class="grid">
<?php
// dummy so that isset($_POST['Order']) passes even when there is only an updated stock number (usu onlu if entering after closing the order)
echo CHtml::hiddenField('Order[items]');
//print_r($model->orderItems);
$this->renderPartial('/orderItems/_edit');
$this->widget('zii.widgets.CListView', array(
	'dataProvider'=>new CArrayDataProvider($model->orderItems),
	'itemView'=>'/orderItems/_edit',
	'viewData' => array('form' => $form),
	'template'=>'{items}'
));
?>
</table>
<?php } ?>

<div class="row buttons">
	<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/orders/_report-buyer.php
<?php
$isHeader = !isset($data);
if ($isHeader) {
	// Link to csv
	if (!$isCsv) echo CHtml::link('Download as CSV', Report::getUrl($report, 1), array('target'=>'_blank'));
	
	function other_orders($m, $csv)
	{
		global $others;
		if ($others == null)
		{
			$others = array();
			foreach ($m as $o) {
				if (!isset($others[$o->user_id])) $others[$o->user_id] = array();
				$others[$o->user_id][$o->id] = $o->formatStatus();
			}
			return;
		}
		
		if (!isset($others[$m->user_id])) return '';
		$oth = $others[$m->user_id];
		$res = array();
		foreach ($oth as $id=>$status) {
			if ($m->id == $id) continue;
			$id = $csv ? $id : CHtml::link($id, array('/orders/' . $id));
			$res[] = sprintf('%s (%s)', $id, $status);
		}
		return implode(', ', $res);
	}
	other_orders($items, 0);

	$cols = explode('	', 'Id	Date	Name	Email	Emp Id	' .
		'Device	Model	IMEI Number	' . //Color
		'Despatcher	Despatcher Ref	' .
		'Contact number	Location	Status	Other(s)');
	if (!$isCsv) {
		$cols[array_search('Location', $cols)] = '<abbr title="(of Billing Address)">Location</abbr>';
		$cols[array_search('Other(s)', $cols)] = '<abbr title="(orders of Same User)">Other(s)</abbr>';
	}
} else {
	$itms = array(array(), array(), array(), array());
	foreach ($data->orderItems as $item)
	{
		$itms[0][] = $item->product->brand;
		$itms[1][] = $item->product->model;
		$itms[2][] = Product::variation_r($item->variation);
		$itms[3][] = $item->stock_nos; // no need to format
	}
	$itemSep = $isCsv ? PHP_EOL : '<br />';
	for ($i = 0; $i <= 3; $i++)
		$itms[$i] = implode($itmSep, $itms[$i]);
	
	$id = $isCsv ? $data->id : CHtml::link($data->id, array('/orders/' . $data->id));
	$add = $data->billingAddress; // since this cannot be the office address
	
	$cells = array($id, Formatter::dateCsv($data->order_date, $isCsv), $data->user->name, $data->user->email, $data->user->employee_id,
		$itms[0], $itms[1], $itms[3], //$itms[2], 
		Formatter::displayObject($data->despatcher, ''), $data->formatDespatcherRef(),
		$add->phone, $add->cityOrPincode(), $data->formatStatus(), other_orders($data, $isCsv)
	);
}

if ($isCsv)
{
	if ($isHeader) header(sprintf('Content-Disposition: attachment; filename=%s-orders-%s-%s.csv', 
		UserIdentity::Context('buyerName'), date('d-M-Y'), 
		str_replace(' ', '-', strtolower(AppEnv::name())) ));
	echo implode(',', $isHeader ? $cols : $cells) . PHP_EOL;

	if ($index == $total - 1) die('');
	return;
}
?>

<tr<?php Formatter::altRow($index); ?>>
<?php if ($isHeader) { ?>
	<th><?php echo implode('</th>' . PHP_EOL . '<th>', $cols); ?></th>
<?php } else { ?>
	<td><?php echo implode('</td>' . PHP_EOL . '<td>', $cells); ?></td>
<?php } ?>
</tr>

protected/views/orders/_view.php
<tr<?php Formatter::altRow($index); ?>>
<?php if (!isset($data)) {
$data = new Order; ?>
	<th><?php echo CHtml::encode($data->getAttributeLabel('id')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('buyer_id')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('user_id')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('address_id')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('order_date')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('status')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('approval')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('amount')); ?></th>
	<th>Despatch Info</th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('verification')); ?></th>
	<th><abbr title="Type, Date, Verification, Purge">Payment</abbr></th>
<?php } else { ?>
	<td><?php echo CHtml::link(CHtml::encode($data->id), array('/orders/view', 'id'=>$data->id));
	if ($this->user_is('superorbuyeradmin') || AppReports::isInReport()) echo ' ' . CHtml::link('&hellip;', array('/orders/update', 'id'=>$data->id)); ?></td>
	<td><?php echo Formatter::displayObject($data->buyer); ?></td>
	<td><?php echo User::link($data->user, $data->buyer); ?></td>
	<td><?php echo $data->formatAddress(); ?></td>
	<td><?php echo Formatter::date($data->order_date); ?></td>
	<td><?php echo AppLookups::OrderStatus($data->status); ?></td>
	<td><?php echo $data->formatApproval(); ?></td>
	<td><?php echo Formatter::amount($data->amount); ?></td>
	<td><?php echo Formatter::displayObject($data->despatcher, '') 
		. ($data->despatcher_reference != null ? ' / ' . $data->despatcher_reference : '')
		. ($data->despatched_date != null ? ' / ' . Formatter::date($data->despatched_date) : ''); ?></td>
	<td><?php echo Order::hideVerification($data); ?></td>
	<td><?php echo Formatter::Concat(' / ', // TODO: ConcatArray
		$data->formatPaymentType(),
		Formatter::date($data->payment_date, 0),
		$data->paymentLinkOrStatus(), $data->purgeLink() ); ?></td>
<?php } ?>
</tr>

protected/views/orders/index.php
<?php
$this->breadcrumbs=array(
	'Orders',
);

$this->menu = MenuHelper::Menu();
?>

<h1>Orders</h1>

<?php if ($actions) FlashMessages::displayActions('/orders/index/', $actions['items'], $actions['selected']); ?>

<table class="grid">
<?php
$this->renderPartial('_view', array('index' => false));
$this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
));
?>
</table>

protected/views/orders/pay.php
<?php
$this->breadcrumbs=array(
	'Orders'=>array('index'),
	$model->id,
);

$this->menu= MenuHelper::Menu($model);
$addr = $model->despatcher != null ? ' <br/>Address: ' . Address::formatEx($model->despatcher) : '';
$pytData = array(
	'Type: %s' => AppLookups::PaymentType($model->payment_type),
	', Ref: %s' => $model->payment_ref,
	', Date: %s' => Formatter::date($model->payment_date, 0),
	', Confirmed: %s' => $model->payment_ref != '' ? Formatter::bool($model->payment_confirmed) : '',
);
if (isset($payLink))
{
	if ($model->needsApprovalOrRejection(1))
		$pytData['<strong>Actions</strong>: %s'] = 'Cannot Pay yet because Approval Pending';
	else if ($model->isRejected())
		$pytData['<strong>Actions</strong>: %s'] = 'Cannot Pay since order rejected.';
	else
	$pytData['<br /><b>Actions</b>: %s'] = $payLink;
}
//print_r($pytData);
?>

<h1>Online Payment Details for Order #<?php echo $model->id; ?></h1>

<?php
$atts = array(
		array('label'=>'Order', 'type'=>'raw', 'value'=>CHtml::link('#' . $model->id, array('/orders/view', 'id'=>$model->id))),
		array('label'=>$model->getAttributeLabel('buyer_id'), 'type'=>'raw', 'value'=>Formatter::displayObject($model->buyer)),
		array('label'=>$model->getAttributeLabel('address_id'), 'type'=>'raw', 'value'=>$model->formatAddress()),
		array('label'=>$model->getAttributeLabel('billing_address_id'), 'type'=>'raw', 'value'=>$model->formatAddress(1)),
		array('label'=>$model->getAttributeLabel('order_date'), 'type'=>'raw', 'value'=>Formatter::date($model->order_date, 1)),
		array('label'=>$model->getAttributeLabel('amount'), 'type'=>'raw', 'value'=>Formatter::amount($model->amount)),
		array('label'=>$model->getAttributeLabel('status'), 'type'=>'raw', 'value'=>AppLookups::OrderStatus($model->status)),
		array('label'=>$model->getAttributeLabel('approval'), 'type'=>'raw', 'value'=>$model->formatApproval()),
		array('label'=>'Payment Info', 'type'=>'raw', 'value'=>Formatter::ConcatArray(' ', $pytData), 
			'cssClass' => isset($payLink) ? 'pytinfo' : ''),
	);

if (isset($details))
{
	$tbl = AppHelper::buildTable(null, 'tblsmall');
	foreach ($details as $key=>$value) $tbl->add_row($key, $value);
	$atts[] = array('label'=> 'Payment Details', 'type'=>'raw', 'value' => $tbl->generate(), 'cssClass' => 'pytdetl');
}

if ($dummy)	$atts[] =
		array('label'=> 'Dummy PG Links', 'type'=>'raw', 'value' => $dummy);

$this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>$atts,
));

if (isset($pgs['amex']))
{
	
	echo '<div class="right" style="margin-top: 20px">' .
		CHtml::image(Yii::app()->baseurl . '/img/pg/amex-logo.png', 'amex', array('height' => 70)) . ' ' .
		CHtml::image(Yii::app()->baseurl . '/img/pg/amex-safekey.jpg', 'amex safekey', array('height' => 70))
		. '</div>';
}
?>

protected/views/orders/update.php
<?php
$this->breadcrumbs=array(
	'Orders'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu= MenuHelper::Menu($model);
Yii::app()->controller->add_script('products', 0);

if (isset($errors) && $errors != null) echo sprintf('<div class="flash-error">%s</div>', $errors);
if (isset($messages) && $messages != null) echo sprintf('<div class="flash-notice">%s</div>', $messages);
?>

<h1>Update Order <?php echo $model->id; ?></h1>
<div id="pvwdiv" style="display:none;"></div>
<?php echo $this->renderPartial('_form', array('model'=>$model, 'addresses' => $addresses)); ?>