protected/controllers/CartController.php
<?php
/**
 * @author Imran Ali Namazi <imran@cselian.com>
 * @link http://tg.cselian.com/showcase/e-vend
 * @copyright Copyright &copy; 2012-2013 cselian.com
 * @license http://tg.cselian.com/licenses/e-vend
 */

class CartController extends Controller
{
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return $this->getAccessRules();
	}

	public function actionAdd()
	{
		if (isset($_POST['singlepid'])) {
			AppLookups::Cart(array()); // clear it
			$items = array($_POST['singlepid'] => array(1, '', ''));
		} else {
		if (!isset($_POST['pid'])) { $this->actionIndex(); return; }
		$pid = $_POST['pid'];
		$qty = $_POST['qty'];
		$varn = $_POST['varn'];
		$mixed = $_POST['mixed'];
		$items = array();

		$cnt = count($qty);
		for ($i = 0; $i < $cnt ; $i++) {
			if ($qty[$i] == "") continue;
			$items[$pid[$i]] = array($qty[$i], $varn[$i], $mixed[$i]);
		}
		} // end not singlepid
		
		//if ($this->officeEmail != null && isset($_POST['buyerName'])) $this->setOrderFor($_POST['buyerName']);
		$model = new Product;
		$sql = 'select * from products where id in ('.implode(", ", array_keys($items)).')';
		$data = $model->findAllBySql($sql);
		$ps = array(); foreach ($data as $i) $ps[$i->id] = $i;
		
		$data = AppLookups::Cart(); // existing items
		foreach ($items as $id=>$itm) {
			$p = $ps[$id];
			$new = array(
				'id'      => $id,
				'qty'     => $itm[0],
				'price'   => AppPricing::getComputed($p),
				'model'   => $p->model,
				'final'   => AppPricing::getComputed($p, 'final'),
				'calc'    => AppPricing::getComputed($p, 'calc'),
				//'options' => array('Size' => 'L', 'Color' => 'Red')
			);
			if ($itm[1] != 'mixed')
			{
				$new['varn'] = $itm[1];
				$data[$id . '-' . $new['varn']] = $new;
			}
			else
			{
				$mix = explode(',', $itm[2]);
				$varns = $p->adjustVariations('array');
				foreach ($mix as $ix=>$v)
				{
					if ($v == '0') continue;
					$new['varn'] = $varns[$ix];
					$new['qty'] = $v;
					$data[$id . '-' . $new['varn']] = $new;
				}
			}
		}
		
		AppLookups::Cart($data);
		$this->actionIndex();
	}

	public function actionIndex()
	{
		if (isset($_POST['edit']))
			$this->_edit();
		
		$buyer = Buyer::model()->findByPk(UserIdentity::context('buyer'));
		$adds = $buyer->myAddresses();
		
		FlashMessages::AddCurrent('Click on ' . CHtml::link('Products', array('/products')) . ' to go back and add more items.' . AppEnv::get('deliveryNotice', 'Delivery Notice') . AppBuyers::ifSponsoredMessage());
		
		$cart = AppLookups::Cart();
		$canBill = 1; $cantBillReason = ''; $billExcl = '';
		
		if (count($adds['bill']) == 0)
		{
			$canBill = 0;
			$billExcl = '<span class="excl">*</span>';
			// TODO: Office addresses in multi city buyers - billing address different from the office 
			$cantBillReason = sprintf('%s You need to have an address. Please  %s and then come back to the cart to proceed.', $billExcl, Controller::user_is('loggedin') ? CHtml::link('add one', array('/addresses/create')) : UserIdentity::signupOrLogin() . ' first');
		}
		
		if (AppBuyers::isSponsored())
		{
			$sponsoredRxn = array();
			$itemRxn = AppBuyers::sponsoredConfig('restrictItems');
			if ($itemRxn && count($cart) > $itemRxn)
				$sponsoredRxn[] = 'total order items must not exceed ' . $itemRxn;

			$qtyRxn = AppBuyers::sponsoredConfig('restrictQuantity');
			if ($qtyRxn)
			{
				foreach ($cart as $i)
				{
					if ($i['qty'] > $qtyRxn)
					{
						$sponsoredRxn[] = ($itemRxn === 1 ? 'item quantity' : 'all item quantities') . ' must not exceed ' . $qtyRxn;
						break;
					}
				}
			}

			if (count($sponsoredRxn) > 0)
			{
				$canBill = 0;
				$cantBillReason .= ($cantBillReason != '' ? '<br /><br />' : '')
					. sprintf('When purchase is sponsored by the company, the %s.', implode(' and the ', $sponsoredRxn) );
			}
		}
		
		$info = array('buyer' => $buyer, 'list' => $adds['obj'], 'caption' => $buyer->nullAddressCaption());
		$this->render('index', array('cart' => $cart, 'addressSidebarInfo' => $info,
			'addresses' => $adds['cbo'], 'userAddresses' => $adds['bill'], 'paymentTypes' => AppBuyers::PaymentTypes(),
			'canBill' => $canBill, 'cantBillReason' => $cantBillReason, 'billExcl' => $billExcl,
			'isGuest' => $this->user_is('guest'),
			'radios' => $this->user_is('buyer') && AppBuyers::isSponsoredWithRadio(),
			));
	}

	public function actionClear()
	{
		unset(Yii::app()->session['cart']);
		FlashMessages::Add('Your Cart has been emptied.');
		$this->redirect(array('/site/index'));
	}

	function _edit()
	{
		$list = AppLookups::Cart();
		$items = array();
		foreach ($list as $i) $items[$i['id'] . '-' . $i['varn']] = $i;
		
		$pid = $_POST['pid'];
		$qty = $_POST['qty'];
		$cnt = count($qty);
		for ($i = 0; $i < $cnt ; $i++) {
			$id = $pid[$i];
			if (!isset($items[$id])) continue; 
			if ($qty[$i] == $items[$id]['qty']) continue;
			$items[$id]['qty'] = $qty[$i];
		}
		
		if (isset($_POST['del']))
		{
			$del = $_POST['del'];
			$cnt = count($del);
			for ($i = 0; $i < $cnt ; $i++) {
				$id = $del[$i];
				if (isset($items[$id])) unset($items[$id]);
			}
		}
		
		//echo "<pre>" . print_r($items, 1) . "</pre>";
		
		// update seems to fail. lets use destroy
		AppLookups::Cart($items);
	}
}

protected/controllers/SiteController.php
<?php
/**
 * @author Imran Ali Namazi <imran@cselian.com>
 * @link http://tg.cselian.com/showcase/e-vend
 * @copyright Copyright &copy; 2012-2013 cselian.com
 * @license http://tg.cselian.com/licenses/e-vend
 */

class SiteController extends Controller
{
	public function filters()
	{
		return array('accessControl');
	}

	public function accessRules()
	{
		$action = $this->getAction()->getId();
		$cant = strtolower($action) == 'admin' && !$this->user_is('superadmin');
		return array(array( !$cant ? 'allow' : 'deny', 'users'=>array('*')));
	}

	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		if (Buyer::isEnteringSite())
		{
			$this->redirect(array('/products'));
		}
		$this->render('index');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest)
	    		echo $error['message'];
	    	else
	        	$this->render('error', $error);
	    }
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		
		if (!isset($_POST['ContactForm']))
		{
			$model->name = Yii::app()->user->name;
			if (isset($_GET['email']))
				$model->email = $_GET['email'];
			else if ($this->user_is('loggedin'))
				$model->email = UserIdentity::context('userEmail');
		}
		
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				AppMails::send('contact', $model);
				//$headers="From: {$model->email}\r\nReply-To: {$model->email}";
				// Yii::app()->params['adminEmail']
				//mail('imran@cselian.com', AppEnv::name() . ' -> ' . $model->subject, $model->body, $headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
			{
				$this->redirect($this->getGotoUrl());
			}
		}
		
		$this->render('login',array('model'=>$model));
	}

	public function actionReset()
	{
		$model=new LoginForm;
		$step = 'begin';
		if (isset($_GET['k']))
		{
			$user = User::model()->find('email = "'.$_GET['e'].'" and reset_code = "'.$_GET['k'].'"');
			if ($user == null)
			{
				FlashMessages::AddCurrent(sprintf("Incorrect Email or Code. Perhaps you already reset with this key once? Please go back and %s again", 
					CHtml::link('reset password', array('/site/reset/'))));
				$this->render('empty');
				return;
			}
			else
			{
				// TODO: reset_date expiry
				$step = 'enter';
			}
		}
		
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			if ($step == 'enter')
			{
				$user->password = md5($model->password);
				$user->reset_code = null;
				$user->save();
				FlashMessages::AddCurrent(sprintf("Your password has been reset, kindly %s with it to proceed", 
					CHtml::link('login', array('/site/login/'))));
				$this->render('empty');
				return;
			}
			else if (($user = User::model()->find('email = "'.$model->email.'"')) == null)
			{
				FlashMessages::AddCurrent(sprintf("Email %s not found", $model->email));
			}
			else
			{
				$user->setResetCode();
				$user->save();
				AppMails::send('userreset', $user);
				FlashMessages::AddCurrent(sprintf("We have sent an email to %s with instructions on how to reset your password", $model->email));
				//$this->redirect(Yii::app()->homeUrl);
			}
		}
		
		$this->render('reset', array('model' => $model, 'resetstep' => $step));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		UserIdentity::clear();
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}

	/**
	 * Admin page with all sorts of actions.
	 */
	public function actionAdmin()
	{
		$data = array();
		$act = null;
		
		if (isset($_GET['action']))
		{
			$act = $_GET['action'];
			if ($act == 'clear')
			{
				AppLookups::clearCache();
				$msg = 'Pricing, Distributor and Buyer Cache cleared';
			}
			else if ($act == 'clearreport')
			{
				AppReports::clearNamesCache();
				$msg = 'Report Names Cache cleared';
			}
			else if ($act == 'emptydb' || $act == 'emptyord')
			{
				if (!AppEnv::get('nonProduction', 'Is Production')) throw new Exception('Cannot empty a Production Database');
				$msg = AppHelper::EmptyDB($act == 'emptyord');
			}
			else if ($act == 'import_distributor' || $act == 'import_buyer' || $act == 'import_address')
			{
				$name = ucfirst(substr($act, 7));
				if (isset($_POST['mailimport'])) {
					$model = MailImporter::getModel($name, $_POST['mailimport']);
					if ($model->save()) {
						$msg = 'Saved ' . $name . ' #' . $model->id;
					}
					else
					{
						$data['error'] = CHtml::errorSummary($model);
						$data['textArea'] = array(
							'label' => 'and try again',
							'name' => 'mailimport',
							'submit' => 'Create ' . $name,
							'atts' => array('rows' => 12, 'cols' => '60'),
							'val' => $_POST['mailimport']
						);
					}
				} else {
					$data['action'] = $act;
					$sample = MailImporter::getSample($name);
					$hints = MailImporter::getHints($name);
					$link = sprintf('<a href="mailto:%s?subject=Inter-Mart New %s Details&body=%s" target="_new">click here</a>',
						Yii::app()->params['adminEmail'], $name, str_replace('
', '%0d%0A', $sample));
					$data['textArea'] = array(
						'label' => 'Fill the content of the textbox or ' . $link . ' to mail it and have it filled',
						'name' => 'mailimport',
						'submit' => 'Create ' . $name,
						'atts' => array('rows' => 12, 'cols' => '50'),
						'val' => $sample,
						'hints' => $hints);
					$msg = 'Showing input format for ' . $name;
				}
			}
			else if ($act == 'viewconfig')
			{
				$p = Yii::app()->params;
				$map = $p['mapCenter'];
				$data['config'] = array(
					'Site Name'=> Yii::app()->name,
					'Site Language'=> Yii::app()->language,
					'Default Distributor'=> array(Distributor::Deflt('link'), 'Set when adding buyer/address'),
					'Admin Email'=> array($p['adminEmail'], 'Used: contact, email import, from of system emails'),
					'Test Email' => array($p['testEmail'] ? $p['testEmail'] : 'NOT SET', 'Mails are sent here for testing'),
					'Address' => $p['address'],
					'Copyright' => '<small>' . sprintf($p['copyright'], date('Y')) . '</small>',
					'Vat Rate' => array($p['vatRate'] . '%', 'Price = DP - Disount + vat'),
					'Map Info' => array(sprintf('%s, %s. %s', $map['address'], $map['pin'], MapHelper::link($map)), 'Shows as Home on some maps in red'),
					//''=>'',
				);
			}
			else if ($act == 'vieworderstatuses')
			{
				$data['listData'] = array(
					'dataProvider'=>new CArrayDataProvider(Order::SampleStatuses()),
					'itemView'=>'/orders/_admin-status',
				);
				$data['listPostData'] = '*What are we trying to display<br/>** Computed Status, based on the condition of the remaining fields. When Status is not created (1), other fields are ignored!';
			}
			else
			{
				$err = 'Action ' . $act . ' undefined';
			}
			
			if (isset($err))
				FlashMessages::AddCurrent($err, 'error');
			else if (isset($msg))
				FlashMessages::AddCurrent($msg);
		}
		
		$actions = array(
			'clear' => 'Clear Cache of Pricing, Distributor and Buyer',
			'import_distributor' => 'Distributor Import via Direct Edit / Email',
			'import_buyer' => 'Buyer Import via Direct Edit / Email',
			'import_address' => 'Buyer Address Import via Direct Edit / Email',
			'viewconfig' => 'View Configurations',
			'vieworderstatuses' => 'View Statuses of Sample Orders',
			);
		if ($this->user_is('dev')) $actions['clearreport'] = 'Clear Cache of Report Names';
		if (AppEnv::get('nonProduction', 'Is Production', false))
		{
			$actions['emptydb'] = 'Empty the Non-production db';
			$actions['emptyord'] = 'Empty Orders, Users + Addresses from the Non-production db';
		}
			
		$data['actions'] = $actions;
		$data['action'] = $act;
		
		$this->render('admin', $data);
	}
}

protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2-vert.php
<?php $this->beginContent('//layouts/main'); ?>
<div id="top-operations">
<?php
$this->widget('zii.widgets.CMenu', array(
		'items'=>$this->menu,
		'htmlOptions'=>array('class'=>'operations'),
	));

?>
</div>
<div id="content" style="padding-top: 10px; clear: both;">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		global $sidebarTop; echo $sidebarTop;
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
		global $sidebarBot; echo $sidebarBot;
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/extra.css" />
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.css" />
	<!--script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js"></script-->
	<?php if (MapHelper::hasMap()) { ?>
	<script src="http://maps.google.com/maps/api/js?sensor=false"type="text/javascript"></script><?php } ?>
	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container <?php echo AppEnv::get('siteBodyCss', 'Site Logo Css Class', ''); ?>" id="page">

<?php
// returns true if the user >= $what
function user_is($what)
{
	return Yii::app()->controller->user_is($what);
}
?>
	<div id="mainMbMenu" class="nav popout">
		<div id="logo"><?php echo UserIdentity::currentUserLink(1); ImgHelper::buyer_logo(); ImgHelper::site_logo(); ?></div>
		<?php
		$cart = user_is('buyer') ? AppLookups::Cart('count') : 0;
		$this->widget('application.extensions.mbmenu.MbMenu',array(
			//'htmlOptions' => array('class' => 'nav'),
			'firstItemCssClass' => 'first',
			'items'=>array(
				array('label'=>'Home', 'url'=>array('/site'), 'items'=> array(
					array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
					array('label'=>'Contact', 'url'=>array('/site/contact')),
					array('label'=>'Terms', 'url'=>array('/site/page', 'view'=>'terms')),
					array('label'=>'Policies', 'url'=>array('/site/page', 'view'=>'policies')),
					)),
				array('label'=>'Administer', 'visible'=>user_is('superadmin'), 'items'=> array(
					array('label'=>'Distributors', 'url'=>array('/distributors/')),
					array('label'=>'Products', 'url'=>array('/products/admin') ,'items'=> array(
						array('label'=>'Create', 'url'=>array('/products/create')))),
					array('label'=>'Pricing', 'url'=>array('/pricing/') ,'items'=> array(
						array('label'=>'Create', 'url'=>array('/pricing/create')))),
					array('label'=>'Buyers', 'url'=>array('/buyers/')),
					array('label'=>'Users', 'url'=>array('/users/admin')),
					array('label'=>'Mail Templates', 'url'=>array('/mails')),
					array('label'=>'Generator', 'url'=>array('/gii'), 'visible' => user_is('dev') && AppEnv::get('gii', 'Enable Code Generator', 0), 'linkOptions' => array('target' => 'new')),
					array('label'=>'Site', 'url'=>array('/site/admin')),
					)),
				array('label'=>'View', 'visible'=>user_is('superadmin'), 'items'=> array(
					array('label'=>'Orders', 'url'=>array('/orders/')),
					array('label'=>'Addresses', 'url'=>array('/addresses/')),
					)),
				array('label'=>'View', 'visible'=>user_is('distributor'), 'items'=> array(
					array('label'=>'Orders', 'url'=>array('/orders/')),
					array('label'=>'Buyers', 'url'=>array('/buyers/')),
					array('label'=>'Products', 'url'=>array('/products/')),
					array('label'=>'Stock', 'url'=>array('/stock/')),
					// array('label'=>'Salesmen', 'url'=>array('/orders/')),
					)),
				array('label'=>'Products', 'url'=>array('/products/'), 'visible'=>user_is('buyer')),
				array('label'=>'Cart (' . $cart . ')', 'url'=>array('/cart'), 'visible'=>$cart, 'items'=> array(
					array('label'=>'Empty Cart', 'url'=>array('/cart/clear')),
					)),
				array('label'=>'Orders', 'url'=>array('/orders/'), 'visible'=>user_is('buyer') && user_is('loggedin')),
				array('label'=>'View', 'visible'=>user_is('salesman'), 'items'=> array(
					array('label'=>'Buyers', 'url'=>array('/buyers/')),
					array('label'=>'Orders', 'url'=>array('/orders/')),
					)),
				AppReports::getMenu(),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>user_is('notloggedin') && !user_is('autologin')),
				array('label'=>'Signup', 'url'=>array('/users/signup'), 'visible'=>user_is('notloggedin') && !user_is('autologin')),
				array('label'=> 'User' , 'visible'=>user_is('loggedin'), 'items'=> array(
					array('label' => Yii::app()->user->name, 'url'=>array('/users/me'), 'linkOptions' => array('title' => UserIdentity::context('userEmail'))),
					UserIdentity::currentUserLink(),
					user_is('buyer') ? array('label'=>'Addresses', 'url'=>array('/addresses/')) : array('visible' => 0),
					array('label'=>'Logout', 'url'=>array('/site/logout/')),
					)),
				array('label'=>'Help', 'url'=>array('/help'), 'items' => MenuHelper::HelpMenu()),
			),
		)); ?>
	<?php if (user_is('admin')) { echo '<div class="nav-item">'; AppLookups::selectUserTypes(); echo '</div>'; } ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php FlashMessages::Display(); ?>
	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright <?php echo sprintf(Yii::app()->params['copyright'], date('Y')); ?>
		<p class="credits">Developed by <a href="http://tg.cselian.com">cselian</a> with <a href="http://www.yiiframework.com/" rel="external">Yii</a>.</p>
		<p class="links"><?php echo CHtml::link('Terms', array('/site/page', 'view'=>'terms'))
		 . ' ' . CHtml::link('Policies', array('/site/page', 'view'=>'policies')); ?></p>
		<?php echo Yii::app()->params['address']; ?><br />
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>