protected/models/Distributor.php
<?php
/**
 * @author Imran Ali Namazi <imran@cselian.com>
 * @link http://tg.cselian.com/showcase/e-vend
 * @copyright Copyright &copy; 2012-2013 cselian.com
 * @license http://tg.cselian.com/licenses/e-vend
 */

/**
 * This is the model class for table "distributors".
 *
 * The followings are the available columns in table 'distributors':
 * @property integer $id
 * @property string $name
 * @property string $date_added
 * @property string $office_email
 * @property string $address
 * @property string $pin
 * @property string $lat
 * @property string $lon
 * @property string $tax_info
 * @property string $payment_info
 */
class Distributor extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Distributor the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	
	function Deflt($ret = 'id')
	{
		$id = AppEnv::get('default_distributor', 'Default Distributor', false);
		if (!$id) return $ret == 'link' ? 'null' : ($ret == 'id' ? null : false);
		if ($ret == 'link')
		{
			$model = self::model()->findByPK($id);
			return CHtml::link(sprintf('%s (#%s)', $model->name, $model->id), array('/distributors/' . $model->id));
		}
		
		return $id;
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'distributors';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, date_added, office_email, address, pin, lat, lon', 'required'),
			array('name, office_email', 'length', 'max'=>100),
			array('address', 'length', 'max'=>255),
			array('pin', 'length', 'max'=>6),
			array('lat, lon', 'length', 'max'=>9),
			array('tax_info, payment_info', 'length', 'max'=>512),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, name, date_added, office_email, address, pin, lat, lon, tax_info, payment_info', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'date_added' => 'Date Added',
			'office_email' => 'Office Email',
			'address' => 'Address',
			'pin' => 'Pin',
			'lat' => 'Lat',
			'lon' => 'Lon',
			'tax_info' => 'Tax Info',
			'payment_info' => 'Payment Info',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('date_added',$this->date_added,true);
		$criteria->compare('office_email',$this->office_email,true);
		$criteria->compare('address',$this->address,true);
		$criteria->compare('pin',$this->pin,true);
		$criteria->compare('lat',$this->lat,true);
		$criteria->compare('lon',$this->lon,true);
		$criteria->compare('tax_info',$this->tax_info,true);
		$criteria->compare('payment_info',$this->payment_info,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/DistributorsController.php
<?php
/**
 * @author Imran Ali Namazi <imran@cselian.com>
 * @link http://tg.cselian.com/showcase/e-vend
 * @copyright Copyright &copy; 2012-2013 cselian.com
 * @license http://tg.cselian.com/licenses/e-vend
 */

class DistributorsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return $this->getAccessRules();
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	public function actionMe()
	{
		$this->actionView(UserIdentity::context('distributor'));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Distributor;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Distributor']))
		{
			$model->attributes=$_POST['Distributor'];
			$model->date_added = Formatter::dateForSql();
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Distributor']))
		{
			$model->attributes=$_POST['Distributor'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Distributor');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	public function actionMap()
	{
		$dataProvider=new CActiveDataProvider('Distributor');
		MapHelper::register();
		$this->render('map',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Distributor('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Distributor']))
			$model->attributes=$_GET['Distributor'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Distributor::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='distributor-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/distributors/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'distributor-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'date_added'); ?>
		<?php if($model->id != null) echo Formatter::date($model->date_added); else echo '<br/>'; ?>
		<?php echo $form->error($model,'date_added'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'office_email'); ?>
		<?php echo $form->textField($model,'office_email',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'office_email'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'address'); ?>
		<?php echo $form->textArea($model,'address',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'address'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'pin'); ?>
		<?php echo $form->textField($model,'pin',array('size'=>6,'maxlength'=>6)); ?>
		<?php echo $form->error($model,'pin'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'lat'); ?>
		<?php echo $form->textField($model,'lat',array('size'=>9,'maxlength'=>9)); ?>
		<?php echo $form->error($model,'lat'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'lon'); ?>
		<?php echo $form->textField($model,'lon',array('size'=>9,'maxlength'=>9)); ?>
		<?php echo $form->error($model,'lon'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'tax_info'); ?>
		<?php echo $form->textArea($model,'tax_info',array('size'=>60,'maxlength'=>512)); ?>
		<?php echo $form->error($model,'tax_info'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'payment_info'); ?>
		<?php echo $form->textArea($model,'payment_info',array('size'=>60,'maxlength'=>512)); ?>
		<?php echo $form->error($model,'payment_info'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/distributors/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'date_added'); ?>
		<?php echo $form->textField($model,'date_added'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'office_email'); ?>
		<?php echo $form->textField($model,'office_email',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'address'); ?>
		<?php echo $form->textField($model,'address',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'pin'); ?>
		<?php echo $form->textField($model,'pin',array('size'=>6,'maxlength'=>6)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'lat'); ?>
		<?php echo $form->textField($model,'lat',array('size'=>9,'maxlength'=>9)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'lon'); ?>
		<?php echo $form->textField($model,'lon',array('size'=>9,'maxlength'=>9)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tax_info'); ?>
		<?php echo $form->textField($model,'tax_info',array('size'=>60,'maxlength'=>512)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'payment_info'); ?>
		<?php echo $form->textField($model,'payment_info',array('size'=>60,'maxlength'=>512)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/distributors/_view.php
<tr<?php Formatter::altRow($index); ?>>
<?php if (!isset($data)) {
$data = new Distributor; ?>
	<th><?php echo CHtml::encode($data->getAttributeLabel('id')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('name')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('date_added')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('office_email')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('address')); ?></th>
	<th><?php echo MapHelper::$linkLabel; ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('tax_info')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('payment_info')); ?></th><?php if (Yii::app()->controller->user_is('superadmin')) { ?>
	<th>Admin</th><?php } ?>
<?php } else { ?>
	<td><?php echo CHtml::link(CHtml::encode($data->id), array('/distributors/view', 'id'=>$data->id));
	if (AppReports::isInReport()) echo ' ' . CHtml::link('&hellip;', array('/distributors/update', 'id'=>$data->id));?></td>
	<td><?php echo CHtml::encode($data->name); ?></td>
	<td><?php echo Formatter::date($data->date_added); ?></td>
	<td><?php echo $data->office_email; ?></td>
	<td><?php echo Address::formatEx($data); ?></td>
	<td><?php echo MapHelper::link($data); ?></td>
	<td><?php echo Formatter::multiline($data->tax_info); ?></td>
	<td><?php echo Formatter::multiline($data->payment_info); ?></td><?php if (Yii::app()->controller->user_is('superadmin')) { ?>
	<th><?php echo User::createFor($data, 0, ''); ?></th><?php } ?>
<?php } ?>
</tr>

protected/views/distributors/admin.php
<?php
$this->breadcrumbs=array(
	'Distributors'=>array('index'),
	'Manage',
);

$this->menu= MenuHelper::Menu();

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('distributor-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Distributors</h1>

<?php
echo CHtml::link('Clear Pricing/Distributor Cache', array('/site/admin?action=clear'), array('target' => '_new', 'class' => 'button')) . '<br /><br />';
?>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'distributor-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'name',
		'date_added',
		'office_email',
		'address',
		'pin',
		'tax_info',
		'payment_info',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/distributors/create.php
<?php
$this->breadcrumbs=array(
	'Distributors'=>array('index'),
	'Create',
);

$this->menu= MenuHelper::Menu();
?>

<h1>Create Distributor</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/distributors/index.php
<?php
$this->breadcrumbs=array(
	'Distributors',
);

$this->menu= MenuHelper::Menu();
?>

<h1>Distributors</h1>

<?php
if (Yii::app()->controller->user_is('superadmin'))
	echo CHtml::link('Clear Pricing/Distributor Cache', array('/site/admin?action=clear'), array('target' => '_new', 'class' => 'button'));
?>

<table class="grid">
<?php
$this->renderPartial('_view', array('index' => false));
$this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
));
?>
</table>

protected/views/distributors/map.php
<?php
$this->breadcrumbs=array(
	'Distributors',
);

$this->menu= MenuHelper::Menu();
?>

<h1>Distributors on the Map</h1>

<div id="map" style="height: 450px; border: double 2px #ccc">Loading Map...</div>
<?php
MapHelper::addHome();
$pts = $dataProvider->getData();
$fmt = '<a href="' . Yii::app()->request->baseUrl . '/distributors/%s">%s</a>';
foreach ($pts as $itm)
	MapHelper::addLocation($itm, $fmt, 'Distributor', 'green');

MapHelper::printMap();
?>

protected/views/distributors/update.php
<?php
$this->breadcrumbs=array(
	'Distributors'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu= MenuHelper::Menu($model);
?>

<h1>Update Distributor <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/distributors/view.php
<?php
$this->breadcrumbs=array(
	'Distributors'=>array('index'),
	$model->name,
);

$this->menu= MenuHelper::Menu($model);
?>

<h1>View Distributor #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'name',
		array('label'=>$model->getAttributeLabel('date_added'), 'type'=>'raw', 'value'=>Formatter::date($model->date_added)),
		'office_email',
		array('label'=>$model->getAttributeLabel('address'), 'type'=>'raw', 'value'=>Address::formatEx($model)),
		array('label'=>MapHelper::$linkLabel, 'type'=>'raw', 'value'=>MapHelper::link($model)),
		array('label'=>$model->getAttributeLabel('tax_info'), 'type'=>'raw', 'value'=>Formatter::multiline($model->tax_info)),
		array('label'=>$model->getAttributeLabel('payment_info'), 'type'=>'raw', 'value'=>Formatter::multiline($model->payment_info)),
	),
)); ?>