protected/models/Buyer.php
<?php
/**
 * @author Imran Ali Namazi <imran@cselian.com>
 * @link http://tg.cselian.com/showcase/e-vend
 * @copyright Copyright &copy; 2012-2013 cselian.com
 * @license http://tg.cselian.com/licenses/e-vend
 */

/**
 * This is the model class for table "buyers".
 *
 * The followings are the available columns in table 'buyers':
 * @property integer $id
 * @property string $date_added
 * @property string $name
 * @property integer $type
 * @property string $contact
 * @property string $notify
 * @property string $address
 * @property string $pin
 * @property string $phone
 * @property string $mobile
 * @property string $lat
 * @property string $lon
 * @property integer $assigned_to_id
 * @property string $outstanding
 * @property string $tax_info
 * @property integer $priced_only
 * @property integer $approval_required
 * @property string $payment_types
 * @property string $signup_from
 * @property integer $sponsored
 * @property integer $purge
 *
 * The followings are the available model relations:
 * @property Address[] $addresses
 * @property Distributor $assignedTo
 * @property Order[] $orders
 * @property Pricing[] $pricings
 * @property User[] $users
 */
class Buyer extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Buyer the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function formatApproval()
	{
		return intval($this->approval_required) === 2 ? 'yes (post pyt)' : Formatter::bool($this->approval_required);
	}

	public static function format($model, $nr = 0)
	{
		return sprintf('%s (%s%s)', $model->name, 
			AppLookups::BuyerType($model->type),
			$nr ? ' #' . $model->id : '');
	}
	
	public static function isEnteringSite($flash = 0)
	{
		if (!isset($_GET['buyer']) || !isset($_GET['id']) || !isset($_GET['hash']))
			return false;
		$id = $_GET['id'];
		$model = self::model()->findByPk($id);
		if ($model == null)
			throw new Exception('Buyer with id' . $id . 'not found');
		if ($model->name != $_GET['buyer'])
			throw new Exception('Buyer id and name do not match. Please ask your admin for the correct url.');
		if (self::hash($model) != $_GET['hash'])
			throw new Exception('Buyer hash invalid. Please ask your admin for the correct url.');

		self::enterSite($id, $model, $flash);
		return true;
	}
	
	public static function isEnteringGlobalBuyerSite($c)
	{
		if ($c->user_is('notloggedin') &&  !$c->user_is('buyer')
			&& 	$c->getId() == 'products' && $id = AppEnv::get('default_buyer', 'Global Buyer Id', 0) )
		{
			self::enterSite($id);
		}
	}
	
	private static function enterSite($id, $model = null, $flash = 0)
	{
		if ($model == null) $model = self::model()->findByPk($id);
		UserIdentity::setContext('buyer', $id);
		UserIdentity::setContext('buyer_type', $model->type); // to throw pricing error
		UserIdentity::setContext('buyerName', $model->name);
		UserIdentity::setUserType(AppLookups::$userTypeBuyer);
		if ($flash) FlashMessages::Add('Feel free to look at the products and add to cart. But before placing an order, you will need to ' . UserIdentity::signupOrLogin() . '.');
	}
	
	public function siteEntryLink()
	{
		$url = Yii::app()->createAbsoluteUrl(sprintf('/?buyer=%s&id=%s&hash=%s', $this->name, $this->id, self::hash($this)));
		return CHtml::link('Buyer Site', $url);
	}
	
	private static function hash($o)
	{
		$id = $o->id;
		$l = str_split($o->name);
		foreach ($l as $a) $id += ord($a);
		return base64_encode($id);
	}
	
	public function adjustPaymentTypes($for = 'view')
	{
		if ($for == 'save')
			$this->payment_types = $this->payment_types != '' ? implode(',', $this->payment_types) : '';
		else if ($for == 'edit')
			$this->payment_types = Formatter::csvToInts($this->payment_types); //checkBoxList uses in_array
		else if ($for == 'view')
			$this->payment_types = AppLookups::PaymentTypes($this->payment_types, 1);
	}
	
	public function nullAddressCaption()
	{
		$admin = UserIdentity::context('admin');
		return $admin ? 'Self' : 'Office';
	}
	
	public function myAddresses()
	{
		$admin = UserIdentity::context('admin');
		$id = UserIdentity::context('user');
		$cbo = array(); //TODO: Office addresses - null => $admin ? 'Self' : 'Office');
		$bill = array();
		$obj = array();
		foreach ($this->addresses as $v)
		{
			// TODO: depends on buyer type? or admin should not be using the admin account for personal orders?
			if (!$admin && $v->user_id != $id) continue;
			$obj[] = $v;
			$cbo[$v->id] = $v->name;
			$bill[$v->id] = $v->name;
		}
		return  array('cbo' => $cbo, 'bill' => $bill, 'obj' => $obj);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'buyers';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('date_added, name, type, contact, address, pin, phone, signup_from', 'required'),
			array('type, assigned_to_id, priced_only, approval_required, sponsored, purge', 'numerical', 'integerOnly'=>true),
			array('name, contact', 'length', 'max'=>100),
			array('notify, tax_info', 'length', 'max'=>512),
			array('address', 'length', 'max'=>255),
			array('pin', 'length', 'max'=>6),
			array('phone, mobile', 'length', 'max'=>50),
			array('lat, lon, outstanding', 'length', 'max'=>9),
			array('payment_types', 'length', 'max'=>32),
			array('signup_from', 'length', 'max'=>1024),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, date_added, name, type, contact, notify, address, pin, phone, mobile, lat, lon, assigned_to_id, outstanding, tax_info, priced_only, approval_required, payment_types, signup_from, sponsored, purge', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'addresses' => array(self::HAS_MANY, 'Address', 'buyer_id'),
			'assignedTo' => array(self::BELONGS_TO, 'Distributor', 'assigned_to_id'),
			'orders' => array(self::HAS_MANY, 'Order', 'buyer_id'),
			'pricings' => array(self::HAS_MANY, 'Pricing', 'buyer_id'),
			'users' => array(self::HAS_MANY, 'User', 'buyer_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'date_added' => 'Date Added',
			'name' => 'Name',
			'type' => 'Type',
			'contact' => 'Contact',
			'notify' => 'Notify',
			'address' => 'Address',
			'pin' => 'Pin',
			'phone' => 'Phone',
			'mobile' => 'Mobile',
			'lat' => 'Lat',
			'lon' => 'Lon',
			'assigned_to_id' => 'Assigned To',
			'outstanding' => 'Outstanding',
			'tax_info' => 'Tax Info',
			'priced_only' => 'Priced Only',
			'approval_required' => 'Approval Required',
			'payment_types' => 'Payment Types',
			'signup_from' => 'Signup From',
			'sponsored' => 'Sponsored',
			'purge' => 'Purge',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('date_added',$this->date_added,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('type',$this->type);
		$criteria->compare('contact',$this->contact,true);
		$criteria->compare('notify',$this->notify,true);
		$criteria->compare('address',$this->address,true);
		$criteria->compare('pin',$this->pin,true);
		$criteria->compare('phone',$this->phone,true);
		$criteria->compare('mobile',$this->mobile,true);
		$criteria->compare('lat',$this->lat,true);
		$criteria->compare('lon',$this->lon,true);
		$criteria->compare('assigned_to_id',$this->assigned_to_id);
		$criteria->compare('outstanding',$this->outstanding,true);
		$criteria->compare('tax_info',$this->tax_info,true);
		$criteria->compare('priced_only',$this->priced_only);
		$criteria->compare('approval_required',$this->approval_required);
		$criteria->compare('payment_types',$this->payment_types,true);
		$criteria->compare('signup_from',$this->signup_from,true);
		$criteria->compare('sponsored',$this->sponsored);
		$criteria->compare('purge',$this->purge);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/BuyersController.php
<?php
/**
 * @author Imran Ali Namazi <imran@cselian.com>
 * @link http://tg.cselian.com/showcase/e-vend
 * @copyright Copyright &copy; 2012-2013 cselian.com
 * @license http://tg.cselian.com/licenses/e-vend
 */

class BuyersController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return $this->getAccessRules();
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model = $this->loadModel($id);
		$model->adjustPaymentTypes('view');
		$this->render('view',array(
			'model'=> $model,
		));
	}

	public function actionMe()
	{
		$this->actionView(UserIdentity::context('buyer'));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Buyer;
		$model->payment_types = '1';
		$model->assigned_to_id = Distributor::Deflt('id');
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Buyer']))
		{
			$model->attributes=$_POST['Buyer'];
			$model->adjustPaymentTypes('save');
			$model->date_added = Formatter::dateForSql();
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}
		else
		{
			$model->adjustPaymentTypes('edit');
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Buyer']))
		{
			$model->attributes=$_POST['Buyer'];
			$model->adjustPaymentTypes('save');
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}
		else
		{
			$model->adjustPaymentTypes('edit');
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$this->menuOnTop();
		$dataProvider=new CActiveDataProvider('Buyer');
		if (self::user_is('distributor') || self::user_is('salesman')) $dataProvider->setCriteria(array('condition' => 'assigned_to_id=' . UserIdentity::context('distributor')));
		$dataProvider->setPagination(false);
		
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	public function actionMap()
	{
		$dataProvider=new CActiveDataProvider('Buyer');
		if (self::user_is('distributor') || self::user_is('salesman')) $dataProvider->setCriteria(array('condition' => 'assigned_to_id=' . UserIdentity::context('distributor')));
		MapHelper::register();
		$this->render('map',array(
			'dataProvider'=>$dataProvider,
		));
	}

	public function actionMapOf($id = null)
	{
		if ($this->user_is('buyer')) $id = UserIdentity::context('buyer');
		
		$model=$this->loadModel($id);
		$points = array($model);
		$dis = array();
		if ($model->assigned_to_id != null)
		{
				$dis[$model->assigned_to_id] = 1;
				$points[] = $model->assignedTo;
		}
		foreach ($model->addresses as $itm)
		{
			$points[] = $itm;
			if ($itm->assigned_to_id != null && !isset($dis[$itm->assigned_to_id]))
			{
				$dis[$itm->assigned_to_id] = 1;
				$points[] = $itm->assignedTo;
			}
		}
		
		$dataProvider=new CArrayDataProvider($points);
		MapHelper::register();
		$this->render('map',array(
			'dataProvider'=>$dataProvider, 'buyer' => $model
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Buyer('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Buyer']))
			$model->attributes=$_GET['Buyer'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Buyer::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='buyer-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/buyers/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'buyer-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'type'); ?>
		<?php echo $form->dropDownList($model,'type', Formatter::includeBlank(AppLookups::$buyerTypes)); ?>
		<?php echo $form->error($model,'type'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'contact'); ?>
		<?php echo $form->textField($model,'contact',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'contact'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'notify'); ?>
		<?php echo $form->textField($model,'notify',array('size'=>60,'maxlength'=>512)); ?>
		<?php echo $form->error($model,'notify'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'address'); ?>
		<?php echo $form->textArea($model,'address',array('rows'=>3, 'cols'=>60, 'maxlength'=>255)); ?>
		<?php echo $form->error($model,'address'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'pin'); ?>
		<?php echo $form->textField($model,'pin',array('size'=>6,'maxlength'=>6)); ?>
		<?php echo $form->error($model,'pin'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'phone'); ?>
		<?php echo $form->textField($model,'phone',array('size'=>50,'maxlength'=>50)); ?>
		<?php echo $form->error($model,'phone'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'mobile'); ?>
		<?php echo $form->textField($model,'mobile',array('size'=>50,'maxlength'=>50)); ?>
		<?php echo $form->error($model,'mobile'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'lat'); ?>
		<?php echo $form->textField($model,'lat',array('size'=>9,'maxlength'=>9)); ?>
		<?php echo $form->error($model,'lat'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'lon'); ?>
		<?php echo $form->textField($model,'lon',array('size'=>9,'maxlength'=>9)); ?>
		<?php echo $form->error($model,'lon'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'assigned_to_id'); ?>
		<?php echo $form->dropDownList($model,'assigned_to_id', Formatter::includeBlank(AppLookups::Distributors())); ?>
		<?php echo $form->error($model,'assigned_to_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'outstanding'); ?>
		<?php echo $form->textField($model,'outstanding',array('size'=>9,'maxlength'=>9)); ?>
		<?php echo $form->error($model,'outstanding'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'tax_info'); ?>
		<?php echo $form->textArea($model,'tax_info',array('rows'=>3, 'cols'=>60, 'maxlength'=>512)); ?>
		<?php echo $form->error($model,'tax_info'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'priced_only'); ?>
		<?php echo $form->checkBox($model,'priced_only'); ?>
		<?php echo $form->error($model,'priced_only'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'approval_required'); ?>
		<?php echo $form->radioButtonList($model,'approval_required', AppLookups::$approvalTypes,
			array('separator' => '', 'template' => '<div class="radio-row">{input} {label}</div>')); ?>
		<?php echo $form->error($model,'approval_required'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'payment_types'); ?>
		<?php echo $form->checkBoxList($model,'payment_types', AppLookups::$paymentTypes,
			array('separator' => '', 'template' => '<div class="radio-row">{input} {label}</div>')); ?>
		<?php echo $form->error($model,'payment_types'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'signup_from'); ?>
		<?php echo $form->textArea($model,'signup_from',array('rows'=>3, 'cols'=>60,'maxlength'=>1024)); ?>
		<?php echo $form->error($model,'signup_from'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'sponsored'); ?>
		<?php echo $form->checkBox($model,'sponsored'); ?>
		<?php echo $form->error($model,'sponsored'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'purge'); ?>
		<?php echo $form->checkBox($model,'purge'); ?>
		<?php echo $form->error($model,'purge'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/buyers/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'contact'); ?>
		<?php echo $form->textField($model,'contact',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'address'); ?>
		<?php echo $form->textField($model,'address',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'pin'); ?>
		<?php echo $form->textField($model,'pin',array('size'=>6,'maxlength'=>6)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'phone'); ?>
		<?php echo $form->textField($model,'phone',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'mobile'); ?>
		<?php echo $form->textField($model,'mobile',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'date_added'); ?>
		<?php echo $form->textField($model,'date_added'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'lat'); ?>
		<?php echo $form->textField($model,'lat',array('size'=>9,'maxlength'=>9)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'lon'); ?>
		<?php echo $form->textField($model,'lon',array('size'=>9,'maxlength'=>9)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'outstanding'); ?>
		<?php echo $form->textField($model,'outstanding',array('size'=>9,'maxlength'=>9)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/buyers/_view.php
<tr<?php Formatter::altRow($index); ?>>
<?php
global $superAdmin;
if (!isset($data)) {
$superAdmin = Controller::user_is('superadmin');
$data = new Buyer; ?>
	<th><?php echo CHtml::encode($data->getAttributeLabel('id')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('name')); ?> /
	<?php echo CHtml::encode($data->getAttributeLabel('contact')); ?></th>
	<th>Logo</th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('type')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('date_added')); ?></th><?php if ($superAdmin) { ?>
	<th><?php echo CHtml::encode($data->getAttributeLabel('outstanding')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('signup_from')); ?></th>
	<th rowspan="2">Admin</th><?php } ?>
</tr>
<tr<?php Formatter::altRow($index); ?>>
	<th></th>
	<th colspan="3"><?php echo CHtml::encode($data->getAttributeLabel('address')); ?></th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('phone')); ?> /
	<?php echo CHtml::encode($data->getAttributeLabel('mobile')); ?></th><?php if ($superAdmin) { ?>
	<th>Priced Only / Appvl <br /> Reqd / Sponsored / Purge</th>
	<th><?php echo CHtml::encode($data->getAttributeLabel('payment_types')); ?></th>
<?php } } else { ?>
	<td><?php echo CHtml::link(CHtml::encode($data->id), array('/buyers/view', 'id'=>$data->id)); ?></td>
	<td><?php echo sprintf('%s (%s)', Formatter::Capitalize($data->name), Formatter::Capitalize($data->contact)); ?></td>
	<td><?php ImgHelper::buyer_logo($data); ?></td>
	<td><?php echo AppLookups::BuyerType($data->type); ?></td>
	<td><?php echo CHtml::encode($data->date_added); ?></td><?php if ($superAdmin) { ?>
	<td><?php echo CHtml::encode($data->outstanding); ?></td>
	<td><?php echo CHtml::encode($data->signup_from); ?></td>
	<td rowspan="2"><?php echo $data->siteEntryLink() . ' ' . User::createFor($data, 0, ''); ?></td><?php } ?>
</tr>
<tr<?php Formatter::altRow($index); ?>>
	<td><?php if ($superAdmin || AppReports::isInReport()) echo ' ' . CHtml::link('&hellip;', array('/buyers/update', 'id'=>$data->id));?></td>
	<td colspan="3"><?php echo Formatter::concat(', ', $data->address, $data->pin)
		. ' ' . MapHelper::link($data, 'map'); ?></td>
	<td><?php echo Formatter::concat(' / ', $data->phone, $data->mobile); ?></td>
	<?php if ($superAdmin) { ?>
	<td><?php echo Formatter::bool($data->priced_only) . ' / ' 
		. $data->formatApproval() . ' / ' . Formatter::bool($data->sponsored) . ' / ' . Formatter::bool($data->purge); ?></td>
	<td><?php $data->adjustPaymentTypes(); echo $data->payment_types; ?></td><?php } ?>
<?php } ?>
</tr>

protected/views/buyers/admin.php
<?php
$this->breadcrumbs=array(
	'Buyers'=>array('index'),
	'Manage',
);

$this->menu= MenuHelper::Menu();

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('buyer-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Buyers</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'buyer-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'name',
		'contact',
		'address',
		'pin',
		/*
		'phone',
		'mobile',
		'date_added',
		'lat',
		'lon',
		'outstanding',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>